apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b9kdp7abz-nodejs 
  janus-idp.io/tekton: b9kdp7abz-nodejs
  backstage.io/kubernetes-id: b9kdp7abz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b9kdp7abz-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml